export const Navigation=[{id:1,
    menu:"Men",
    submenu:[{ name: 'Tshirt', href: '#' },
      { name: 'Pant',href: '#'},
      { name: 'Jeans',  href: '#'},
      { name: 'Sweater', href: '#'},
      { name: 'shorts', href: '#'},
      { name: 'Shirt', href: '#'},
      { name: 'Shocks', href: '#'},
      { name: 'Underwear', href: '#'},
      { name: 'Jacket', href: '#'},
      { name: 'cap', href: '#'}]
  },{id:2,
    menu:"Women",
    submenu:[{ name: 'Tshirt', href: '#' },
      { name: 'Pant',href: '#'},
      { name: 'Jeans',  href: '#'},
      { name: 'Trouser', href: '#'},
      { name: 'Top', href: '#'},
      { name: 'Sari', href: '#'},
      { name: 'Underwear', href: '#'},
      { name: 'Scarf', href: '#'},
      { name: 'Trouser', href: '#'},
      { name: 'Trouser', href: '#'},
      { name: 'Trouser', href: '#'},
      { name: 'cap', href: '#'}]
  },
  {id:3,
    menu:"Kids",
    submenu:[{ name: 'Tshirt', href: '#' },
      { name: 'Pant',href: '#'},
      { name: 'Jeans',  href: '#'},
      { name: 'Trouser', href: '#'},
      { name: 'Trouser', href: '#'},
      { name: 'Trouser', href: '#'},
      { name: 'Trouser', href: '#'},
      { name: 'Trouser', href: '#'},
      { name: 'Trouser', href: '#'},
      { name: 'Trouser', href: '#'},
      { name: 'Trouser', href: '#'},
      { name: 'cap', href: '#'}]
  },
  {id:4,
    menu:"Accesories",
    submenu:[{ name: 'Watch', href: '#' },
      { name: 'Ring',href: '#'},
      { name: 'Belt',  href: '#'},
      { name: 'Bag', href: '#'},
      { name: 'Handbeg', href: '#'},
      { name: 'Tie', href: '#'},
      { name: 'Buttons', href: '#'},
      { name: 'Shoes', href: '#'},
      { name: 'Sendalls', href: '#'},
      { name: 'Trouser', href: '#'},
      { name: 'Trouser', href: '#'},
      { name: 'cap', href: '#'}]
  },
  {id:5,
    menu:"Studio",
    submenu:[{ name: 'Tshirt', href: '#' },
      { name: 'Trends',href: '#'},
      { name: 'zara',  href: '#'},
      { name: 'H&T', href: '#'},
      { name: 'tata', href: '#'},
      { name: 'Unique', href: '#'},
      { name: 'Artist', href: '#'}]
  }]
